### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by NaokiTsuchiya**
- profile to spec
- update composer dependencies
- update docs

### CODE REVIEW

**Review by acio-o9 — APPROVED** [review]
LGTM 👍

**Review by koriym — APPROVED** [review]
LGTM

**Review by poemn — APPROVED** [review]
LGTM 👍

**Review by shotanue — APPROVED** [review]
LGTM 👍

**Review by acio-o9 — APPROVED** [review]
LGTM !!!!!!!!!

**Pull request merged**
